--- 
title: "Statistical Process Control in Healthcare"
author: "Sydney Paul, Dwight Barry, Brendan Bettinger, and Andrew Cooper"
date: "`r format(Sys.Date(), '%B %Y')`"
site: bookdown::bookdown_site

output: bookdown::html_book
documentclass: book
# output:
#   bookdown::pdf_book:
#     pandoc_args: ["--listings"]
classoption: openany
fontsize: 12pt
geometry: margin=1in

urlcolor: blue
linkcolor: blue

github-repo: sydneykpaul/spc_healthcare
description: "Using SPC methods in healthcare can be tricky. We show you how to do it correctly."
---  

```{r setup, include=FALSE}
# Global options
knitr::opts_chunk$set(warning = FALSE, message = FALSE, comment = NA, highlight = TRUE, fig.height = 3.5)

# options("width" = 54)
knitr::opts_chunk$set(fig.pos = 'H')

# Load libraries
library(dplyr)
library(scales)
library(lubridate)
library(forecast) 
library(ggseas)
library(qicharts2)
library(bookdown)
library(knitr)
library(ggplot2)
library(ggExtra)
library(gridExtra)
library(pander)
```

# Preface {-}


## We have a problem {#preface_problem}

Statistical process control (SPC) was a triumph of manufacturing analytics, and its success spread across a variety of industries---most improbably, into healthcare.  

Healthcare is rarely compatible with the idea of an assembly line, but lean manufacturing thinking ("Lean") has taken over healthcare management around the world, and SPC methods are common tools in Lean.  

Unlike in manufacturing, stability is an inherently tricky concept in healthcare, so this has led to much *misuse* of these methods. Bad methods lead to bad inferences, and bad inferences can lead to poor decisions.  

This book aims to help analysts apply SPC methods more accurately in healthcare, using the statistical software R.  


## Common questions {#preface_questions}

### _Who is this book for?_ {-}
This book is geared toward analysts working in the healthcare industry, who are already familiar with basic SPC methods and concepts. We do cover some basics, but we focus primarily on the areas that cause the most misunderstandings and misuse; The section [Useful References](#useful_resources) in the Additional Resources chapter provides a great place to start or continue learning about SPC.


### _What do I need to start?_ {-}
  
OVERVIEW AND LINK TO SHINY APP.


## About {#preface_about}

### _Who are we?_ {-}

We are all analysts at *Seattle Children's Hospital* in Seattle, Washington, USA.  

* Sydney Paul is a Data Science Intern in *Enterprise Analytics*.

* Dwight Barry is a Principal Data Scientist in *Enterprise Analytics*. Twitter: \@healthstatsdude  

* Brendan Bettinger is a Senior Analyst in *Infection Prevention*. 

* Andy Cooper is a Principal Data Scientist in *Enterprise Analytics*. Twitter: \@DataSciABC




### _What if I find a typo?_ {-}

You can submit pull requests for any errors or typos at https://github.com/sydneykpaul/spc_healthcare_with_r.

